language: node_js
node_js:
- "8"
cache:
  directories:
    - "node_modules"
before_install:
- npm i -g npm@5.x
- openssl aes-256-cbc -K $encrypted_18b95b300614_key -iv $encrypted_18b95b300614_iv
  -in DESandoval-net-5892a0e8d050.json.enc -out DESandoval-net-5892a0e8d050.json -d
install:
- npm install
script:
- npm run build
deploy:
  provider: gae
  keyfile: DESandoval-net-5892a0e8d050.json
  project: desandoval-net
  verbosity: debug
  on: master
